language: python
python: 
 - "2.7"
 - "3.5"

sudo: false

addons:
  apt:
    packages:
    - python-dev 
    - build-essential 
    - mysql-server 
    - mysql-client 
    - graphviz 
    - python-pip 
    - python-numpy 
    - git 
    - libmysqlclient-dev
    - docbook
    - python-apt
    - dblatex
    - texlive-latex-extra 
    - docbook-utils
    - inkscape
    - libxml2-dev
    - libxslt1-dev

env:
- PYTHONPATH=. CAIRIS_SRC=$PYTHONPATH/cairis CAIRIS_CFG=cairis_travis.cnf XML_CATALOG_FILES=$CAIRIS_SRC/config/catalog $CAIRIS_CFG_DIR=./travisConfig

install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
- pip install coveralls

script: 
- py.test cairis/test --doctest-modules -v --cov cairis/core cairis/daemon cairis/controllers cairis/data cairis/tools --cov-report term-missing

after_success:
- coveralls
- codecov 
