# Site wide configuration

title: CAIRIS
description: Computer Aided Integration of Requirements and Information Security
logo: logo.gif # 120x120 px default image used for Twitter summary card
teaser: teaser.gif # 400x250 px default teaser image used in image archive grid
locale:
url: http://cairis.org
# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
  syntax_highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist


# Site owner
owner:
  name: Shamal Faily
  web: http://shamalfaily.com
  twitter: CAIRISApp
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
